name: Build .NET Library

on:
  pull_request:
    branches: [ develop, main ]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    - name: Install dependencies
      run: dotnet restore qatoolkit-engine-httptester-net.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: qatoolkit-engine-httptester-net.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: src/QAToolKit.Engine.HttpTester/bin/
  deploy:
    name: Pack and Push Nuget
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Pack NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/QAToolKit.Engine.HttpTester/QAToolKit.Engine.HttpTester.csproj
        VERSION_FILE_PATH: Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_COMMIT: true